# process names are case-insensitive
# you can use 'master' to indicate the master channel or a list of process names to create a group
slider_mapping:
  0: discord.exe
  1:                            #Internet and streaming
    - chrome.exe
    - msedge.exe              #Microsoft edge
    - launcher.exe            #Opera
    - netflix.exe
    - crunchyroll.exe
    - twitch.exe
  2: whatsapp.exe
  3: rocketleague.exe
  4: spotify.exe
  5: master

button_mapping:
  0: q
  1: w
  2: e
  3: r
  4:
    - w
    - t
  5: y
  6: u
  7: i
  8: o
  9: p
  10: a
  11: s

# recommend to leave this setting at its default value
process_refresh_frequency: 5

# settings for connecting to the arduino board
com_port: COM3          # Set to port to the port the keyboard is connected to
baud_rate: 9600         # 9600 is set as default by arduino. Chanching not advised!
