# process names are case-insensitive
# you can use 'master' to indicate the master channel or a list of process names to create a group
slider_mapping:
  0: master
  1:                         #currently nothing
  2:
      - chrome.exe
      - msedge.exe           #Microsoft edge
  3: whatsapp.exe
  4:
      - discord.exe
      - zoom.exe
  5:
      - spotify.exe
      - twitchui.exe        #twitch client
      - cr.winapp.exe       #crunchyroll
      - netflix.exe

button_mapping:
  0: F1
  1: F2
  2: F3
  3: F4
  4: F5
  5: F6
  6: F7
  7: F8
  8: F9
  9: F10
  10: F11
  11: F12

# recommend to leave these setting at there default values
process_refresh_frequency: 5

# settings for connecting to the arduino board
com_port: COM3          # Set to port to the port the keyboard is connected to
baud_rate: 9600         # 9600 is set as default by arduino. Chanching not advised!
